version: 2.1

jobs:
  image-buildx:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f buildx/Dockerfile \
            --progress plain \
            buildx/
      - run: |
          docker buildx ls
  image-caddyproxy:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f caddyproxy/Dockerfile \
            --progress plain \
            caddyproxy/
      - run: |
          docker buildx ls
  image-figlet:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f figlet/Dockerfile \
            --progress plain \
            figlet/
      - run: |
          docker buildx ls
  image-github_changelog_generator:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f github_changelog_generator/Dockerfile \
            --progress plain \
            github_changelog_generator/
      - run: |
          docker buildx ls
  image-gomplate-ci-build:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f gomplate-ci-build/Dockerfile \
            --progress plain \
            gomplate-ci-build/
      - run: |
          docker buildx ls
  image-jwt:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f jwt/Dockerfile \
            --progress plain \
            jwt/
      - run: |
          docker buildx ls
  image-man:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f man/Dockerfile \
            --progress plain \
            man/
      - run: |
          docker buildx ls
  image-nodejs-ci-build:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f nodejs-ci-build/Dockerfile \
            --progress plain \
            nodejs-ci-build/
      - run: |
          docker buildx ls
  image-raspbian:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f raspbian/Dockerfile \
            --progress plain \
            raspbian/
      - run: |
          docker buildx ls
  image-remarkjs:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f remarkjs/Dockerfile \
            --progress plain \
            remarkjs/
      - run: |
          docker buildx ls
  image-sed:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f sed/Dockerfile \
            --progress plain \
            sed/
      - run: |
          docker buildx ls
  image-socat:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f socat/Dockerfile \
            --progress plain \
            socat/
      - run: |
          docker buildx ls
  image-ssh:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f ssh/Dockerfile \
            --progress plain \
            ssh/
      - run: |
          docker buildx ls
  image-trx:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f trx/Dockerfile \
            --progress plain \
            trx/
      - run: |
          docker buildx ls
  image-upx:
    docker:
      - image: hairyhenderson/docker-buildx
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - run: |
          docker buildx create \
            --name builder \
            --use \
            $DOCKER_HOST
      - run: |
          docker buildx build \
            -f upx/Dockerfile \
            --progress plain \
            upx/
      - run: |
          docker buildx ls

workflows:
  version: 2
  build_docker_images:
    jobs:
      - image-buildx
      - image-caddyproxy
      - image-figlet
      - image-github_changelog_generator
      - image-gomplate-ci-build
      - image-jwt
      - image-man
      - image-nodejs-ci-build
      - image-raspbian
      - image-remarkjs
      - image-sed
      - image-socat
      - image-ssh
      - image-trx
      - image-upx
